name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]
    
jobs:
  prod-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        id: checkout
        
      - name: doxygen clone
        run: git clone https://github.com/doxygen/doxygen.git
           
