name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]
    
jobs:
  prod-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout
        
      - name: run doxygen
        run: |
          pwd
          sudo apt-get install doxygen
          doxygen Doxyfile
