name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [ labeled ]
    
jobs:
  prod-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        id: checkout
        
      - name: doxygen change directory
        run: cd doxygen
        
      - name: make directory build
        run: mkdir build; cd build
        
      - name: cmake
        run: cmake -G "Unix Makefiles" ..
           
